# Generated by Django 5.0.4 on 2024-04-26 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото машины'),
        ),
    ]
