# Generated by Django 5.0.4 on 2024-04-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_rename_car_carimg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Цена машины'),
        ),
    ]
