# Generated by Django 5.0.4 on 2024-05-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=800, verbose_name='Описание машины'),
        ),
    ]
