# Generated by Django 5.0.4 on 2024-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=250, verbose_name='Цена машины'),
        ),
    ]
