# Generated by Django 5.0.4 on 2024-05-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_car_name_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='carimg',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Название машины'),
        ),
    ]
