# Generated by Django 5.0.4 on 2024-05-08 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_car_category_alter_carimg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimg',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='car.car', verbose_name='Название машины'),
        ),
    ]
