# Generated by Django 5.0.4 on 2024-05-08 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_activation_code_userpasswords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_active',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Активационный код'),
        ),
        migrations.AlterField(
            model_name='userpasswords',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userpasswords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_passwords', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
